### ISSUE TITLE
[May be a severe Bug] DB Too many clients already

### ISSUE THREAD

**Issue by kmahyyg** [Syslifters/sysreptor#201]
Opened two project and each project opened a "notes" tab + a "reporting" tab.
Then after a few hours, the system down.
This account is 2FA-enabled.
Last known-working version is 2024.3, `2024.8` I didn't test it thoroughly because after a few hours I upgraded to 2024.8, you released 2024.10, so I continuously upgraded from 2024.3 to 2024.8 to 2024.10.

Check Container Logs:

PGSQL Log from `docker logs`:
```
{"log":"2024-01-25 16:19:46.036 UTC [1] LOG:  starting PostgreSQL 14.10 (Debian 14.10-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit\n","stream":"stderr","time":"2024-01-25T16:19:46.03615927Z"}
{"log":"2024-01-25 16:19:46.038 UTC [1] LOG:  listening on IPv4 address \"0.0.0.0\", port 5432\n","stream":"stderr","time":"2024-01-25T16:19:46.038312376Z"}
{"log":"2024-01-25 16:19:46.038 UTC [1] LOG:  listening on IPv6 address \"::\", port 5432\n","stream":"stderr","time":"2024-01-25T16:19:46.03831646Z"}
{"log":"2024-01-25 16:19:46.063 UTC [1] LOG:  listening on Unix socket \"/var/run/postgresql/.s.PGSQL.5432\"\n","stream":"stderr","time":"2024-01-25T16:19:46.063374615Z"}
{"log":"2024-01-25 16:19:46.096 UTC [26] LOG:  database system was shut down at 2024-01-25 16:19:24 UTC\n","stream":"stderr","time":"2024-01-25T16:19:46.096301998Z"}
{"log":"2024-01-25 16:19:46.172 UTC [1] LOG:  database system is ready to accept connections\n","stream":"stderr","time":"2024-01-25T16:19:46.172109104Z"}
{"log":"2024-01-27 08:53:37.533 UTC [570638] FATAL:  sorry, too many clients already\n","stream":"stderr","time":"2024-01-27T08:53:37.534336692Z"}
{"log":"2024-01-27 08:53:38.033 UTC [570646] FATAL:  sorry, too many clients already\n","stream":"stderr","time":"2024-01-27T08:53:38.033814281Z"}
{"log":"2024-01-27 08:53:40.116 UTC [570653] FATAL:  sorry, too many clients already\n","stream":"stderr","time":"2024-01-27T08:53:40.117047Z"}
{"log":"2024-01-27 08:53:42.202 UTC [570661] FATAL:  sorry, too many clients already\n","stream":"stderr","time":"2024-01-27T08:53:42.202347192Z"}
{"log":"2024-01-27 08:53:44.267 UTC [570669] FATAL:  sorry, too many clients already\n","stream":"stderr","time":"2024-01-27T08:53:44.267200292Z"}
{"log":"2024-01-27 08:53:46.356 UTC [570678] FATAL:  sorry, too many clients already\n","stream":"stderr","time":"2024-01-27T08:53:46.356101955Z"}
{"log":"2024-01-27 08:53:48.420 UTC [570686] FATAL:  sorry, too many clients already\n","stream":"stderr","time":"2024-01-27T08:53:48.421102659Z"}
{"log":"2024-01-27 08:53:50.483 UTC [570694] FATAL:  sorry, too many clients already\n","stream":"stderr","time":"2024-01-27T08:53:50.484041857Z"}
{"log":"2024-01-27 08:53:52.570 UTC [570702] FATAL:  sorry, too many clients already\n","stream":"stderr","time":"2024-01-27T08:53:52.570743653Z"}
{"log":"2024-01-27 08:53:54.657 UTC [570710] FATAL:  sorry, too many clients already\n","stream":"stderr","time":"2024-01-27T08:53:54.657551046Z"}
{"log":"2024-01-27 08:53:56.751 UTC [570718] FATAL:  sorry, too many clients already\n","stream":"stderr","time":"2024-01-27T08:53:56.751923362Z"}
{"log":"2024-01-27 08:53:58.813 UTC [570726] FATAL:  sorry, too many clients already\n","stream":"stderr","time":"2024-01-27T08:53:58.813757434Z"}
{"log":"2024-01-27 08:53:59.938 UTC [570727] FATAL:  sorry, too many clients already\n","stream":"stderr","time":"2024-01-27T08:53:59.938414222Z"}
{"log":"2024-01-27 08:54:00.898 UTC [570736] FATAL:  sorry, too many clients already\n","stream":"stderr","time":"2024-01-27T08:54:00.898701618Z"}
<Repeat till die>
```

APP Health Check from `docker inspect` :

```
            "StartedAt": "2024-01-25T16:19:45.37330439Z",
            "FinishedAt": "2024-01-27T12:23:27.210467496Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 7,
                "Log": [
                    {
                        "Start": "2024-01-27T20:21:02.060772773+08:00",
```

APP Log from `docker logs`:

```
2024-01-27 08:52:37,671 [INFO] root: GET /api/v1/pentestprojects/66e71623-b46d-4ee8-a5f2-fb10171c9704/ 200 (user=REDACTED)
2024-01-27 08:52:37,694 [INFO] root: GET /api/v1/pentestprojects/d92955a4-fa2f-4468-8cd1-f2def7869090/ 200 (user=REDACTED)
2024-01-27 08:52:37,705 [INFO] root: GET /api/v1/pentestprojects/d92955a4-fa2f-4468-8cd1-f2def7869090/notes/ 200 (user=REDACTED)
2024-01-27 08:53:37,599 [INFO] root: GET /api/v1/pentestprojects/66e71623-b46d-4ee8-a5f2-fb10171c9704/ 200 (user=REDACTED)
2024-01-27 08:53:37,621 [INFO] root: POST /api/v1/pentestprojects/d92955a4-fa2f-4468-8cd1-f2def7869090/sections/network_pentest_walkthrough/lock/ 200 (user=REDACTED)
2024-01-27 08:53:37,623 [INFO] root: GET /api/v1/pentestprojects/d92955a4-fa2f-4468-8cd1-f2def7869090/ 200 (user=REDACTED)
2024-01-27 08:53:37,634 [INFO] root: GET /api/v1/pentestprojects/d92955a4-fa2f-4468-8cd1-f2def7869090/notes/ 200 (user=REDACTED)
2024-01-27 08:53:59,938 [ERROR] root: connection failed: FATAL:  sorry, too many clients already
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/connection.py", line 749, in connect
    raise last_ex.with_traceback(None)
psycopg.OperationalError: connection failed: FATAL:  sorry, too many clients already

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/adrf/viewsets.py", line 115, in async_view
    return await self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/adrf/views.py", line 66, in async_dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/adrf/views.py", line 61, in async_dispatch
    response = await handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/reportcreator_api/api_utils/views.py", line 140, in healthcheck
    await PeriodicTask.objects.run_all_pending_tasks()
  File "/app/api/reportcreator_api/tasks/querysets.py", line 78, in run_all_pending_tasks
    for t in await sync_to_async(self.get_pending_tasks)():
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/reportcreator_api/tasks/querysets.py", line 18, in get_pending_tasks
    for t in self.filter(id__in=pending_tasks.keys()):
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 316, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 292, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/connection.py", line 749, in connect
    raise last_ex.with_traceback(None)
django.db.utils.OperationalError: connection failed: FATAL:  sorry, too many clients already
2024-01-27 08:54:30,030 [ERROR] root: connection failed: FATAL:  sorry, too many clients already
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/connection.py", line 749, in connect
    raise last_ex.with_traceback(None)
psycopg.OperationalError: connection failed: FATAL:  sorry, too many clients already

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/adrf/viewsets.py", line 115, in async_view
    return await self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/adrf/views.py", line 66, in async_dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/adrf/views.py", line 61, in async_dispatch
    response = await handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/reportcreator_api/api_utils/views.py", line 140, in healthcheck
    await PeriodicTask.objects.run_all_pending_tasks()
  File "/app/api/reportcreator_api/tasks/querysets.py", line 78, in run_all_pending_tasks
    for t in await sync_to_async(self.get_pending_tasks)():
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/reportcreator_api/tasks/querysets.py", line 18, in get_pending_tasks
    for t in self.filter(id__in=pending_tasks.keys()):
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 316, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 292, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/connection.py", line 749, in connect
    raise last_ex.with_traceback(None)
django.db.utils.OperationalError: connection failed: FATAL:  sorry, too many clients already
2024-01-27 08:54:37,600 [INFO] root: GET /api/v1/pentestprojects/66e71623-b46d-4ee8-a5f2-fb10171c9704/ 200 (user=REDACTED)
2024-01-27 08:54:37,604 [INFO] root: GET /api/v1/pentestprojects/d92955a4-fa2f-4468-8cd1-f2def7869090/notes/ 200 (user=REDACTED)
2024-01-27 08:54:37,638 [INFO] root: GET /api/v1/pentestprojects/d92955a4-fa2f-4468-8cd1-f2def7869090/ 200 (user=REDACTED)
2024-01-27 08:55:37,612 [INFO] root: GET /api/v1/pentestprojects/d92955a4-fa2f-4468-8cd1-f2def7869090/ 200 (user=REDACTED)
2024-01-27 08:56:00,214 [ERROR] root: connection failed: FATAL:  sorry, too many clients already
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/connection.py", line 749, in connect
    raise last_ex.with_traceback(None)
psycopg.OperationalError: connection failed: FATAL:  sorry, too many clients already

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/adrf/viewsets.py", line 115, in async_view
    return await self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/adrf/views.py", line 66, in async_dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/adrf/views.py", line 61, in async_dispatch
    response = await handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/reportcreator_api/api_utils/views.py", line 140, in healthcheck
    await PeriodicTask.objects.run_all_pending_tasks()
  File "/app/api/reportcreator_api/tasks/querysets.py", line 78, in run_all_pending_tasks
    for t in await sync_to_async(self.get_pending_tasks)():
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/reportcreator_api/tasks/querysets.py", line 18, in get_pending_tasks
    for t in self.filter(id__in=pending_tasks.keys()):
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 316, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 292, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/connection.py", line 749, in connect
    raise last_ex.with_traceback(None)
django.db.utils.OperationalError: connection failed: FATAL:  sorry, too many clients already
```

**Comment by kmahyyg** [comment]
It seems to be incorrectly use of database connection pool.

**Comment by MWedl** [comment]
Hi, thanks for reporting. After some time of investigating and debugging, we found that the root cause of this bug is in the django framework. Django does not reliably call the `request_finished` signal in ASGI servers, where database connections are closed. This leads to many stale DB connections filling up the postgres connection limit. See also https://code.djangoproject.com/ticket/35059 for more details.

**Comment by kmahyyg** [comment]
> Hi, thanks for reporting. After some time of investigating and debugging, we found that the root cause of this bug is in the django framework. Django does not reliably call the `request_finished` signal in ASGI servers, where database connections are closed. This leads to many stale DB connections filling up the postgres connection limit. See also https://code.djangoproject.com/ticket/35059 for more details.

Seems upstream merged and created a new git tag.

**Comment by MWedl** [comment]
Updated django in https://github.com/Syslifters/sysreptor/releases/tag/2024.13
