### ISSUE TITLE
Upload Issue

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#247]
I am using a relatively older version (few months ago) of Sysreptor, but I don't think it's something that's been fixed "yet".

When I upload a new image I get this following error and then it responds on the web application with a 500 Internal Server Error.

```
2024-05-02 06:26:24,734 [INFO] root: Function compress_image took 0:00:01.080682
2024-05-02 06:26:24,737 [ERROR] root: [Errno 13] Permission denied: '/data/uploadedimages/a0/6e43fa-2ad9-4065-83fb-672866a0582e'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.10/site-packages/adrf/viewsets.py", line 115, in async_view
    return await self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/adrf/views.py", line 66, in async_dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
```

It's having problems uploading the image I think?

As of right now I cannot seem to upload images or anything any more.

**Comment by aronmolnar** [comment]
Hi Vincent,

I seems the Docker volume where the uploads are stored have wrong permissions.

You might be able to fix the issue by entering your app container as root (`docker exec -u root -it sysreptor-app /bin/bash`) and change the owner (or permissions) of `/data` using `chown -R 0:0 /data`

**Comment by vysecurity** [comment]
I redeployed it but I'll keep the comment here for reference in future! Thank you Aron!.\
