### ISSUE TITLE
Aw, Snap! Error when rendering PDF

### ISSUE THREAD

**Issue by richardschwabe** [Syslifters/sysreptor#50]
Problem:
Using Version 0.96
Whenever I go into the designer I get a `Aw,Snap!` Chrome error once it is rendering the PDF

![image](https://github.com/Syslifters/sysreptor/assets/63605187/283b00ec-a72d-4044-8f58-6ab37aa848d5)

This is the output of the docker container logs
```
2023-06-22 10:11:41,595 [INFO] root: POST /api/v1/projecttypes/26cd20a9-2346-40f5-83d9-df7a971c86ac/lock/ 201 (user=reptor)
2023-06-22 10:11:42,982 [INFO] root: Function render_to_html took 0:00:01.388239
2023-06-22 10:11:43,816 [INFO] root: Function render_to_pdf took 0:00:00.833481
2023-06-22 10:11:43,816 [INFO] root: Function encrypt_pdf took 0:00:00.000003
2023-06-22 10:11:43,819 [INFO] root: Function render_pdf_task took 0:00:02.224996
2023-06-22 10:11:43,830 [INFO] root: POST /api/v1/projecttypes/26cd20a9-2346-40f5-83d9-df7a971c86ac/preview/ 200 (user=reptor)
```

This happens with the Demo Calzone v1.0, the Matrix 1.0 and the Margherita v1.0 design, as well as my own template.

It also happens when I try to render an actual report and not just in the designer.

I used the `update.sh` file to update to the latest version.

**Comment by aronmolnar** [comment]
Hi Richard,

Can you check whether you see anything in the Dev Tools console?
And can you post your exact Chrome version?
(could not reproduce the error with latest Chrome and Brave)

**Comment by richardschwabe** [comment]
```
Google Chrome | 114.0.5735.106 (Official Build) (64-bit)
-- | --
Revision | 5148e93c94b4990618801dd6918f26936be770f9-refs/branch-heads/5735_90@{#9}
OS | Linux
JavaScript | V8 11.4.183.19


```
![image](https://github.com/Syslifters/sysreptor/assets/63605187/10b723d3-0d56-414f-a931-907fd33cd769)

Console Output:

![image](https://github.com/Syslifters/sysreptor/assets/63605187/b839a829-18ea-4fd0-a2a1-0339e564feda)


Raw Console Output

```
api.js:140 Uncaught (in promise) Error: Invalid PDF binary data: either TypedArray, string, or array-like object is expected in the data property.
    at getDocument (api.js:140:1)
    at Object.open (app.js:655:1)
    at index.js:97:31
getDocument @ api.js:140
open @ app.js:655
(anonymous) @ index.js:97
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
_onData @ contentscript.js:1
_onMessage @ contentscript.js:1
postMessage (async)
_postMessage @ inpage.js:1
_write @ inpage.js:1
_handshake @ inpage.js:1
l @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
1.../../shared/modules/provider-injection @ inpage.js:1
i @ inpage.js:1
e @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ contentscript.js:1
1.../../shared/constants/app @ contentscript.js:1
i @ contentscript.js:1
e @ contentscript.js:1
(anonymous) @ contentscript.js:1
api.js:140 Uncaught (in promise) Error: Invalid PDF binary data: either TypedArray, string, or array-like object is expected in the data property.
    at getDocument (api.js:140:1)
    at Object.open (app.js:655:1)
    at index.js:97:31
getDocument @ api.js:140
open @ app.js:655
(anonymous) @ index.js:97
postMessage (async)
_postMessage @ inpage.js:1
_write @ inpage.js:1
_onData @ inpage.js:1
_onMessage @ inpage.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
_handshake @ contentscript.js:1
l @ contentscript.js:1
(anonymous) @ contentscript.js:1
ie @ contentscript.js:1
1.../../shared/constants/app @ contentscript.js:1
i @ contentscript.js:1
e @ contentscript.js:1
(anonymous) @ contentscript.js:1
2api.js:140 Uncaught (in promise) Error: Invalid PDF binary data: either TypedArray, string, or array-like object is expected in the data property.
    at getDocument (api.js:140:1)
    at Object.open (app.js:655:1)
    at index.js:97:31
getDocument @ api.js:140
open @ app.js:655
(anonymous) @ index.js:97
postMessage (async)
_postMessage @ inpage.js:1
_write @ inpage.js:1
b @ inpage.js:1
_ @ inpage.js:1
v.uncork @ inpage.js:1
_onData @ inpage.js:1
_onMessage @ inpage.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
_onData @ contentscript.js:1
_onMessage @ contentscript.js:1
postMessage (async)
_postMessage @ inpage.js:1
_write @ inpage.js:1
_handshake @ inpage.js:1
l @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
1.../../shared/modules/provider-injection @ inpage.js:1
i @ inpage.js:1
e @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ contentscript.js:1
1.../../shared/constants/app @ contentscript.js:1
i @ contentscript.js:1
e @ contentscript.js:1
(anonymous) @ contentscript.js:1
3api.js:140 Uncaught (in promise) Error: Invalid PDF binary data: either TypedArray, string, or array-like object is expected in the data property.
    at getDocument (api.js:140:1)
    at Object.open (app.js:655:1)
    at index.js:97:31
```

**Comment by aronmolnar** [comment]
Can you try to run the rendering process in an incognito tab? Maybe there is some browser caching issue.


If this does not work, can you rebuild your containers by going to `deploy` and running `docker compose -f docker-compose.yml build --no-cache --pull` and `docker compose -f docker-compose.yml up -d`

(The output looks quite strange because the line numbers of the js files do not fit to the current or last version of pdfjs.)

**Comment by aronmolnar** [comment]
I suspect that one of your JavaScript files of the old version was cached (but not in incognito mode).

We will have a look if we can resolve this issue on our side (e.g. by setting http headers).
