### ISSUE TITLE
Install fails because of outdated demo data

### ISSUE THREAD

**Issue by firefart** [Syslifters/sysreptor#62]
Hi,
the install script is currently failing without an error because stderr is redericted to /dev/null on importing of the templates. If I run the command by hand the error shows up and seems to be related to the recent translation changes.

```text
curl -s "$url" | docker compose exec --no-TTY app python3 manage.py importdemodata --type=template
2023-08-02 20:16:56,291 [ERROR] reportcreator_api.archive.import_export.import_export: Error while importing archive. Rolling back import.
Traceback (most recent call last):
  File "/app/api/reportcreator_api/archive/import_export/import_export.py", line 155, in import_archive
    raise error
  File "/app/api/reportcreator_api/archive/import_export/import_export.py", line 146, in import_archive
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'format': [ErrorDetail(string='Invalid format: expected "templates/v2" got "templates/v1"', code='invalid')], 'translations': [ErrorDetail(string='This field is required.', code='required')]}
Traceback (most recent call last):
  File "/app/api/manage.py", line 22, in <module>
    main()
  File "/app/api/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/app/api/reportcreator_api/management/commands/importdemodata.py", line 46, in handle
    imported = import_func(f)
  File "/app/api/reportcreator_api/archive/import_export/import_export.py", line 196, in import_templates
    return import_archive(archive_file, serializer_classes=[FindingTemplateExportImportSerializerV2, FindingTemplateImportSerializerV1], context={'uploaded_by': uploaded_by})
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/app/api/reportcreator_api/archive/import_export/import_export.py", line 170, in import_archive
    raise ex
  File "/app/api/reportcreator_api/archive/import_export/import_export.py", line 155, in import_archive
    raise error
  File "/app/api/reportcreator_api/archive/import_export/import_export.py", line 146, in import_archive
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'format': [ErrorDetail(string='Invalid format: expected "templates/v2" got "templates/v1"', code='invalid')], 'translations': [ErrorDetail(string='This field is required.', code='required')]}
```

**Comment by aronmolnar** [comment]
Thank you for reporting this.  
Just fixed this by upgrading the demo templates to v2.

However, we need to take a look to support importing v1 templates due to backwards compatibility.

**Comment by firefart** [comment]
BTW: The install.sh script does not check return codes of the imports and simply exits, Maybe you can implement a return code check to let the user know there was an error

**Comment by aronmolnar** [comment]
Yes, this is the plan.
We currently redirect 2>/dev/null because the output of the import is not that beautiful and our custom script currently does not respect the --verbosity switch of Django's manage.py.

We should remove the stderr redirection to see the error directly.

**Comment by aronmolnar** [comment]
Import stderr is no longer redirected to stderr. In case of an exception, the user should see the error message.

https://github.com/Syslifters/sysreptor-docs/blob/a57a78af612de85ac2d6883ca7faf5c288e0e7ce/install.sh#L133
